### ISSUE TITLE
Images not rendering (solution)

### ISSUE THREAD

**Issue by Havaria** [pavittarx/editorjs-html#1]
Need close "img" tag on this part:

> return `<img src="${data.file.url}" alt="${caption}">`;

**Comment by pavittarx** [comment]
@Havaria Thank you for letting me know. 

* This have been fixed along with many other major changes.  

In addition to this, I would like you to know that, you can override default parser function in the same manner, as you would write a custom function. So, that can help you to define your own personal HTML Markup or make some temporary fixes for yourself.
