### ISSUE TITLE
paragraph transformation in source twice

### ISSUE THREAD

**Issue by groteworld** [pavittarx/editorjs-html#11]
on [Line #27]( https://github.com/pavittarx/editorjs-html/blob/master/src/transforms.js#L27) it has another paragraph transformation. Is this purposeful or just oversight? I'm doing some general cleanup and wondering if I'm missing something by removing this?

Thanks!

**Comment by pavittarx** [comment]
@groteworld 
It is simply an oversight, nothing purposeful. I have been keeping this cleanup for next update, but there is nothing in general I can provide as next update. I have tried to avoid introducing any unintended complexity keeping the library flexible as much as possible, which have so far been the initial goal.
However, Thanks for looking into it and letting me know.  :heart:
