### ISSUE TITLE
Unnecessary white spaces for before/after HTML tags

### ISSUE THREAD

**Issue by georgelemon** [pavittarx/editorjs-html#15]
Hey, I'm using this in order to achieve a stats bar that will show how many lines, words, chars and spaces a document contains and I realized that there are some extra unnecessary white spaces in your code.

I suggest to remove the [white spaces before/after HTML tags](https://github.com/pavittarx/editorjs-html/blob/c7f21e718cbbada01bc5f97149f64102276d8886/src/transforms.ts#L34) for all your default transforms.

Also, transforming the delimiter can be a good idea to be `hr` instead of `br`

**Comment by pavittarx** [comment]
@georgelemon whitespaces were added for code readability. However, has been removed.

`delimiter` will remain br for code consistency, and to be in-line with previous versions. However, you can always override defaults with your own. 

https://github.com/pavittarx/editorjs-html#extend-for-custom-blocks

Change `type` to field you want to override. For example `{type: 'delimiter'}` in your case.
