### ISSUE TITLE
Image doesn't work

### ISSUE THREAD

**Issue by akisantos** [pavittarx/editorjs-html#16]
![image](https://user-images.githubusercontent.com/38753836/101989794-61b6c280-3cd5-11eb-9516-972f97c5349d.png)

**Comment by pavittarx** [comment]
@akisantos can your provide me with some copy of your generated data, specifically the blocks with the issue.

**Comment by akisantos** [comment]
> @akisantos can your provide me with some copy of your generated data, specifically the blocks with the issue.

I edit codes  myself and it's work. Here is code i changed:
image:function(t){var e=t.data,url=e.url,n=e.caption?e.caption:"Image";;return'<img src="'+(url)+'" alt="'+n+'" />'}.

**Comment by pavittarx** [comment]
@akisantos If you feel issues with the default parser functions, or if they don't work the way you want them to. You can always override them with your own. Overrides are written in the same way you would write a function for a custom block.

* Docs: https://github.com/pavittarx/editorjs-html#extend-for-custom-blocks
* Code Examples: https://runkit.com/pavittarx/editorjs-html-example

However, I'll see to this and fix this over here itself.

**Comment by akisantos** [comment]
@pavittarx cool, keep it up. Thank you very much!
