### ISSUE TITLE
Conditional params problem

### ISSUE THREAD

**Issue by timofeyp** [pavittarx/editorjs-html#21]
I've tried to initialize parser in class constructor, with different quote block parsers depends on boolean condition.
In both cases just one quote parser was used - a boolean condition always used as last, but passed different.
 
It seems like always HtmlParser called, it being re-initialized. How to get two different instances of parser ?

[codesandbox here](https://codesandbox.io/s/beautiful-brattain-cbzz1?file=/src/index.js)

**Comment by pavittarx** [comment]
Hello @timofeyp 
Thank you for taking time to post this. I am aware of this issue, yet I am a little short on time for contributions to this project. I'll surely see into this.
