### ISSUE TITLE
Block not being parsed should throw an exception

### ISSUE THREAD

**Issue by mikeoaklet** [pavittarx/editorjs-html#24]
Hi

I ran into situation trying to parse data with one embed block, which is not supported. Then, `parser.parse()` returned an empty object for that one block., which is quite inconvenient. I would suggest throwing an `UnsupportedBlock` exception or similar in such cases with hint to make custom implementation for that block type.

**Comment by pavittarx** [comment]
Hey @mikeoaklet 
Can you please provide me with the data of the block, so that I can know. Since, the library is supposed to throw exceptions when it encounters unknown blocks.

**Comment by mikeoaklet** [comment]
I already solved it in my project adding custom parser. Give me please few days to finish a sprint and I will try to reproduce this.

**Comment by mikeoaklet** [comment]
@pavittarx Ok, I reproduced and found out the issue. Basically, what I do on the server is something like this:
```js
const edjsParser = edjsHtml()

return edjsParser.parse(edjsCleanData).join('\n')
```

And lib returns array of html strings. When there is an exception it is part of the array, right.

So the exception gets stringified and joined to the actual HTML output. I guess, this is intentional, so you can iterate over returned array and handle exception in a way, you need - probably skip.

The problem with this solution is, in my opinion, that this isn't the kind of exception you want to handle in runtime, you want to solve this in development phase. Because of that, I would probably suggest to throw an exception from the parse method, when there is an unsupported block - so it forces you to add block parser.

**Comment by pavittarx** [comment]
Thanks @mikeoaklet for taking your time to report this. This makes sense. I'll deploy a fix to this soon enough.
