### ISSUE TITLE
Feature request to support Nested lists

### ISSUE THREAD

**Issue by Kunal-KP** [pavittarx/editorjs-html#31]
Currently the library is not supporting the nested list plugin: https://github.com/editor-js/nested-list

It is treating it as an object.

<img width="861" alt="Screenshot 2021-06-24 at 1 18 36 PM" src="https://user-images.githubusercontent.com/21334786/123223755-c9ed2900-d4ee-11eb-9cf7-db0a7c6dc00a.png">

<img width="844" alt="Screenshot 2021-06-24 at 1 18 46 PM" src="https://user-images.githubusercontent.com/21334786/123223787-cfe30a00-d4ee-11eb-81d2-b98a4847f81f.png">

Can you please help in extending support to nested lists?

**Comment by pavittarx** [comment]
@Kunal-KP 
Can you provide me the data for the block with nested list? So, that I can adjust the parser accordingly.

Thanks!

**Comment by Kunal-KP** [comment]
@pavittarx 
Please find the data for the block below:
{
  "time": 1624729628176,
  "blocks": [
    {
      "id": "cd2B3X4vsx",
      "type": "list",
      "data": {
        "style": "ordered",
        "items": [
          {
            "content": "List 1 Header 1",
            "items": [
              {
                "content": "List 1 Sub header 1",
                "items": []
              },
              {
                "content": "List 1 Sub header 2",
                "items": [
                  {
                    "content": "List 1 Sub header 1 Sub Sub header 1",
                    "items": []
                  },
                  {
                    "content": "List 1 Sub header 1 Sub Sub header 2",
                    "items": []
                  }
                ]
              }
            ]
          },
          {
            "content": "List 2 Header 1",
            "items": [
              {
                "content": "List 2 Sub header 1",
                "items": []
              },
              {
                "content": "List 2 Sub header 2",
                "items": []
              }
            ]
          }
        ]
      }
    }
  ],
  "version": "2.22.0"
}

Also, I have added a recursion logic to implement this functionality in your package. It's working fine. Please find the relevant piece of code and see if you can improve upon it.

In editorjs-html/src/transforms.ts:

```
  list: ({ data }) => {
    let style = data.style === "unordered" ? "ul" : "ol";
    let list = "";
    if (data.items) {
      // TO DO: Check if the data type first item in data.items is string or object
      // If string, use the existing library code to return the list items
      // If object, use the below recurse function to iterate recursively over the nested list
      return recurse(data.items,style)   
    }
    return `<${style}>${list}</${style}>`;
  },
```

recursive function in the same file mentioned above:

```
const recurse = (items: any,style:string) => {
  console.log('inside recurse')
  let content_list = `<${style}>`
  for(let i=0;i<items.length;i++) {
  	content_list += `<li>` + items[i]["content"] + `</li>`
    if(items[i]['items'] && items[i]['items'].length == 0){
    	continue
    }   	
    else {
    	content_list += recurse(items[i]['items'],style)
    }    	
  }
  content_list += `</${style}>`
  return content_list
}
```

One suggestion:
Since the list package (https://www.npmjs.com/package/@editorjs/list) and the nested list package (https://github.com/editor-js/nested-list), both use the list keyword, a type check on the items array can help in differentiating the two implementations as mentioned in the commented code above.

Hope this helps :)

**Comment by pavittarx** [comment]
the library now suporrts both normal as well as nested lists.

**Comment by Kunal-KP** [comment]
Thanks :)
