### ISSUE TITLE
Unable to resolve URL in image

### ISSUE THREAD

**Issue by jiagnhu** [pavittarx/editorjs-html#32]
Perhaps it is because editorjs has been updated and the data structure has changed. There is no file object in the parameter of image, so data cannot be obtained
![image](https://user-images.githubusercontent.com/30381575/128481434-203e6fd0-bbbb-4df0-ba9a-c4af7b687e9c.png)

**Comment by Chaitanya-yash** [comment]
Yep, facing the same problem. The image as following: <img src="undefined" alt="Image" />
@pavittarx

**Comment by Chaitanya-yash** [comment]
![image](https://user-images.githubusercontent.com/83573847/132326944-9e15a106-1d7f-4e3a-b467-006dca24df62.png)
The transform function wants data.file.url, while it should only be data.url
Tried this today. Requesting @pavittarx if you can update it. I am not sure if this would fix it.

**Comment by pavittarx** [comment]
Thanks, @Chaitanya-yash for pointing that out. This has been updated.
