### ISSUE TITLE
Heading permalink

### ISSUE THREAD

**Issue by BenjaminHoegh** [pavittarx/editorjs-html#33]
Is there a way in the current version of editorjs-html to have it make heading permalinks?

**Comment by pavittarx** [comment]
@BenjaminHoegh you can provide  a custom parser function, and structure headings as per your needs.

https://github.com/pavittarx/editorjs-html#extend-for-custom-blocks

Note: the key passed to edjsHTML is the block type you want to provide the parser function or override.
