### ISSUE TITLE
Quote alignment

### ISSUE THREAD

**Issue by azatka** [pavittarx/editorjs-html#35]
Left alignment not working
![image](https://user-images.githubusercontent.com/55189325/159159212-af74449a-a401-486c-bd0f-9e1ac633b110.png)
![image](https://user-images.githubusercontent.com/55189325/159159267-fb06723d-06a6-4d4e-8a57-8c40ef6b25e6.png)

**Comment by pavittarx** [comment]
1. Check the CSS styles, if any styles you provided are affecting the current element. Also, you can provide your own styles, since editorjs-html does not add any styling on its own. 
2. You can always define your own parser functions to better suit your needs. 

I hope that helps.
