### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by RaymondSalim** [pavittarx/editorjs-html#47]
Looks like the latest release was almost 2 years ago. 

The NPM Package also does not have the latest files, despite it saying version `3.4.2`. 

![image](https://github.com/pavittarx/editorjs-html/assets/59678005/6ce17ce2-b9ef-4f46-a294-1fe38bb3cfdd)
![image](https://github.com/pavittarx/editorjs-html/assets/59678005/705038f4-a665-4ea3-8f0f-f5638c45e216)

**Comment by pavittarx** [comment]
I wanted to do an overhaul, but didn't get time to do so. Also, I am no longer maintaining it, just making amends or accepting PR's. I'll check into the issue you pointed.

**Comment by pavittarx** [comment]
released a new version, changes are in there.
