### ISSUE TITLE
It seems that forcing lowercase letters makes it impossible to have uppercase letters in customer tags

### ISSUE THREAD

**Issue by sparklog** [pavittarx/editorjs-html#56]
hello there,
I have create a function to handle `checklist` as following:
```typescript
function checkLisParser(block: CheckListBlock) {
  const items = block.data.items;
  const parsedItems = items.map(item => (
    `<div class="flex">
      <Checkbox checked=${item.checked ? true : false} />
      <p>${item.text}</p>
    </div>`
  )).join('');
  const html = `<div>${parsedItems}</div>`;
  return html;
```
it works, however, the<Checkbox>  has been parsed to checkbox. Thus, I cannot use my component which I have created.

Is there sth I have missed? Thanks

**Comment by pavittarx** [comment]
You will also need to plug-in your parser like this, or it will be skipped over. 
https://github.com/pavittarx/editorjs-html?tab=readme-ov-file#extend-for-custom-blocks
