### ISSUE TITLE
editorjs-mjml

### ISSUE THREAD

**Issue by aliuadepoju** [pavittarx/editorjs-html#8]
Hi Team, please I need a guide on how to modify editorjs-html to editorjs-mjml?

**Comment by pavittarx** [comment]
You will need to define your own parser functions for that. You can also override the default parser functions. Please refer to this section in the docs. 
* https://github.com/pavittarx/editorjs-html#extend-for-custom-blocks

Here is a code example to help you further: https://runkit.com/pavittarx/editorjs-html-example

The only difference would be that you would be replacing `html` with `mjml`. If you still have questions, feel free to get in touch.
